In [1]:
import pandas as pd

df = pd.read_csv("D:\SEMESTER 4\BIG DATA\HASIL SCRAPPING\dataset_gabungan.csv")
df.head()

<>:3: SyntaxWarning: invalid escape sequence '\S'
<>:3: SyntaxWarning: invalid escape sequence '\S'
C:\Users\Vina Nur\AppData\Local\Temp\ipykernel_18296\3954099281.py:3: SyntaxWarning: invalid escape sequence '\S'
  df = pd.read_csv("D:\SEMESTER 4\BIG DATA\HASIL SCRAPPING\dataset_gabungan.csv")

        article   timestamp  views
0  San_Junipero  2016072700      7
1  San_Junipero  2016072800     28
2  San_Junipero  2016072900      7
3  San_Junipero  2016073000     15
4  San_Junipero  2016073100     10

In [2]:
df.shape

(125027705, 3)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125027705 entries, 0 to 125027704
Data columns (total 3 columns):
 #   Column     Dtype
---  ------     -----
 0   article    object
 1   timestamp  int64
 2   views      int64
dtypes: int64(2), object(1)
memory usage: 2.8+ GB

In [4]:
df.isnull().sum()

article      7674
timestamp       0
views           0
dtype: int64

In [5]:
df = df.dropna()

In [6]:
df.duplicated().sum()

16785090

In [7]:
df = df.drop_duplicates()

In [8]:
df.shape

(108234941, 3)

In [12]:
# Convert timestamp ke datetime
df['timestamp'] = pd.to_datetime(df['timestamp'], format='%Y%m%d%H')

In [13]:
df['views'] = pd.to_numeric(df['views'], errors='coerce')
df= df.dropna(subset=['views'])
df= df[df['views'] > 0]

In [14]:
NON_ARTICLE_PREFIXES = [
    'Wikipedia:', 'Help:', 'Portal:', 'Template:', 'File:',
    'Special:', 'Talk:', 'User:', 'Category:', 'Draft:',
    'Book:', 'TimedText:', 'Module:', 'MediaWiki:', 'Main_Page', '404.php'
]

df = df[
    ~df['article'].str.startswith(tuple(NON_ARTICLE_PREFIXES))
]

In [16]:
NON_ARTICLE_PREFIXES_ID = [
    # Namespace Indonesia
    'Wikipedia:', 'Wikipedia_talk:',
    'Bantuan:', 'Bantuan_talk:',
    'Portal:', 'Portal_talk:',
    'Templat:', 'Templat_talk:',
    'Berkas:', 'Berkas_talk:',
    'Istimewa:',
    'Pembicaraan:',
    'Pengguna:', 'Pengguna_talk:',
    'Kategori:', 'Kategori_talk:',
    'Buram:',
    'Buku:',
    'Modul:',
    'MediaWiki:',
]

df = df[
    ~df['article'].str.startswith(tuple(NON_ARTICLE_PREFIXES_ID))
]

print(f"Sesudah filter non-artikel: {df.shape}")

Sesudah filter non-artikel: (106288445, 3)

In [18]:
df['year']  = df['timestamp'].dt.year.astype('int16')
df['month'] = df['timestamp'].dt.month.astype('int8')
df['day']   = df['timestamp'].dt.day.astype('int8')

In [19]:
df = df.sort_values(by='timestamp')

In [22]:
print("=== RINGKASAN DATA ===")
print(f"Data setelah preprocessing : {len(df):,}")
print(f"Missing sesudah            : {df.isnull().sum().sum()}")

# cek duplikat per chunk biar hemat RAM
chunk_size = 1_000_000
dup_count = 0
for i in range(0, len(df), chunk_size):
    chunk = df.iloc[i:i+chunk_size]
    dup_count += chunk.duplicated().sum()
print(f"Duplikat sesudah           : {dup_count:,}")

print(df.dtypes)
print(df.head())

=== RINGKASAN DATA ===
Data setelah preprocessing : 106,288,445
Missing sesudah            : 0
Duplikat sesudah           : 0
article              object
timestamp    datetime64[ns]
views                 int64
year                  int16
month                  int8
day                    int8
dtype: object
                           article  timestamp  views  year  month  day
7890421       The_Call_of_the_Wild 2015-08-01    769  2015      8    1
25585176           Cyrus_the_Great 2015-08-01   2139  2015      8    1
98801619       Titanic_(film_1997) 2015-08-01    229  2015      8    1
2054056              Halimah_Yacob 2015-08-01    207  2015      8    1
123908128  Ekonomi_Amerika_Serikat 2015-08-01     67  2015      8    1

In [23]:
print("\nData setelah preprocessing:")
print(df.head())

Data setelah preprocessing:
                           article  timestamp  views  year  month  day
7890421       The_Call_of_the_Wild 2015-08-01    769  2015      8    1
25585176           Cyrus_the_Great 2015-08-01   2139  2015      8    1
98801619       Titanic_(film_1997) 2015-08-01    229  2015      8    1
2054056              Halimah_Yacob 2015-08-01    207  2015      8    1
123908128  Ekonomi_Amerika_Serikat 2015-08-01     67  2015      8    1

In [24]:
df.describe()

,timestamp,views,year,month,day
count,106288445,1.062884e+08,1.062884e+08,1.062884e+08,1.062884e+08
mean,2021-03-25 21:14:30.525150208,1.573612e+03,2.020724e+03,6.614582e+00,1.574620e+01
min,2015-08-01 00:00:00,1.000000e+00,2.015000e+03,1.000000e+00,1.000000e+00
25%,2018-09-25 00:00:00,6.000000e+01,2.018000e+03,4.000000e+00,8.000000e+00
50%,2021-06-02 00:00:00,3.130000e+02,2.021000e+03,7.000000e+00,1.600000e+01
75%,2023-11-03 00:00:00,1.375000e+03,2.023000e+03,1.000000e+01,2.300000e+01
max,2026-01-31 00:00:00,1.495413e+07,2.026000e+03,1.200000e+01,3.100000e+01
std,NaN,8.833547e+03,3.003575e+00,3.483228e+00,8.803640e+00